# Generated by Django 4.2.6 on 2024-01-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
